# -*- coding: utf-8 -*-
"""LAB 01  ejercicio4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MfLS3rYNqDfRBRdmcXCRjs7Rtrdsl7-C
"""



# ─────────────────────────────────────────────────────────────
# Sistema de Recomendación de Cursos - EPIS - Maria Ezcurra
# ─────────────────────────────────────────────────────────────

import chromadb
from chromadb.utils import embedding_functions

# Cliente persistente (guarda datos en disco)
client = chromadb.PersistentClient(path="./db_cursos")

embedding_fn = embedding_functions.SentenceTransformerEmbeddingFunction()

collection = client.get_or_create_collection(
    name="cursos_epis",
    embedding_function=embedding_fn
)

# Verificar si ya hay datos
if collection.count() == 0:

    cursos = [
        {
            "nombre": "Programación I",
            "descripcion": "Curso introductorio a la programación. Se estudian algoritmos y estructuras básicas. Incluye práctica en Python.",
            "creditos": 4,
            "semestre": 1,
            "area": "basica",
            "prerequisitos": "Ninguno"
        },
        {
            "nombre": "Estructuras de Datos",
            "descripcion": "Estudio de listas, pilas y árboles. Se analizan algoritmos eficientes. Aplicaciones prácticas en software.",
            "creditos": 4,
            "semestre": 3,
            "area": "especialidad",
            "prerequisitos": "Programación I"
        },
        {
            "nombre": "Ingeniería de sistemas",
            "descripcion": "Estudio de sistemas. Se analizan algoritmos eficientes. Aplicaciones prácticas en software.",
            "creditos": 3,
            "semestre": 2,
            "area": "especialidad",
            "prerequisitos": "Programación I"
        },
        {
            "nombre": "Estructuras de Sistemas",
            "descripcion": "Se analizan sistemas eficientes. Aplicaciones prácticas en software.",
            "creditos": 4,
            "semestre": 3,
            "area": "especialidad",
            "prerequisitos": "Programación I"
        },
        {
            "nombre": "Programación II",
            "descripcion": "Desarrollo de programas más complejos.",
            "creditos": 4,
            "semestre": 2,
            "area": "especialidad",
            "prerequisitos": "Programación I"
        },
        {
            "nombre": "Algoritmos",
            "descripcion": "Diseño y análisis de soluciones computacionales.",
            "creditos": 4,
            "semestre": 4,
            "area": "especialidad",
            "prerequisitos": "Programación I"
        },
        {
            "nombre": "Bases de Datos",
            "descripcion": "Gestión y almacenamiento de información.",
            "creditos": 4,
            "semestre": 4,
            "area": "electivo",
            "prerequisitos": "Programación I"
        },
        {
            "nombre": "Sistemas Operativos",
            "descripcion": "Funcionamiento interno de computadoras.",
            "creditos": 4,
            "semestre": 5,
            "area": "especialidad",
            "prerequisitos": "Programación I"
        },
        {
            "nombre": "Redes de Computadoras",
            "descripcion": "Comunicación entre dispositivos.",
            "creditos": 4,
            "semestre": 5,
            "area": "electivo",
            "prerequisitos": "Programación I"
        },
        {
            "nombre": "Arquitectura de Computadores",
            "descripcion": "Diseño del hardware y componentes.",
            "creditos": 4,
            "semestre": 6,
            "area": "especialidad",
            "prerequisitos": "Programación I"
        },
        {
            "nombre": "Matemática Discreta",
            "descripcion": "Fundamentos matemáticos de la computación.",
            "creditos": 4,
            "semestre": 6,
            "area": "especialidad",
            "prerequisitos": "Programación I"
        },
        {
            "nombre": "Cálculo Diferencial",
            "descripcion": "Estudio de cambios y funciones.",
            "creditos": 2,
            "semestre": 7,
            "area": "especialidad",
            "prerequisitos": "Programación I"
        },
        {
            "nombre": "Probabilidad y Estadística",
            "descripcion": "Análisis de datos y predicciones.",
            "creditos": 4,
            "semestre": 7,
            "area": "electivo",
            "prerequisitos": "Programación I"
        },
        {
            "nombre": "Ciberseguridad",
            "descripcion": "Protección de sistemas y datos.",
            "creditos": 3,
            "semestre": 8,
            "area": "especialidad",
            "prerequisitos": "Programación I"
        },
        {
            "nombre": "Desarrollo Web",
            "descripcion": "Creación de aplicaciones en internet.",
            "creditos": 4,
            "semestre": 8,
            "area": "especialidad",
            "prerequisitos": "Programación I"
        },
        {
            "nombre": "Desarrollo Móvil",
            "descripcion": "Aplicaciones para smartphones.",
            "creditos": 2,
            "semestre": 9,
            "area": "especialidad",
            "prerequisitos": "Programación I"
        },
        {
            "nombre": "DevOps",
            "descripcion": "Integración de desarrollo y operaciones.",
            "creditos": 2,
            "semestre": 9,
            "area": "especialidad",
            "prerequisitos": "Programación I"
        },
        {
            "nombre": "Cloud Computing",
            "descripcion": "Uso de servicios en la nube.",
            "creditos": 4,
            "semestre": 3,
            "area": "especialidad",
            "prerequisitos": "Programación I"
        },
        {
            "nombre": "Gestión de Proyectos TI",
            "descripcion": "Planificación de proyectos tecnológicos.",
            "creditos": 4,
            "semestre": 9,
            "area": "especialidad",
            "prerequisitos": "Programación I"
        },
        {
            "nombre": "Sistemas de Información",
            "descripcion": "Soluciones tecnológicas para empresas.",
            "creditos": 4,
            "semestre": 10,
            "area": "especialidad",
            "prerequisitos": "Programación I"
        },
    ]

    documentos = [c["descripcion"] for c in cursos]
    ids = [f"curso_{i}" for i in range(len(cursos))]
    metadatos = cursos

    collection.add(documents=documentos, metadatas=metadatos, ids=ids)

    print(" Cursos insertados")
else:
    print(" Base de datos ya existente")

def recomendar_cursos(intereses_alumno, semestre_actual, top_k=5):
    """
    Recomienda cursos según intereses del alumno y semestre.
    """

    resultados = collection.query(
        query_texts=[intereses_alumno],
        n_results=top_k,
        where={"semestre": {"$gte": semestre_actual}},
        include=['documents', 'metadatas', 'distances']
    )

    print("\n Recomendaciones:")
    print("=" * 50)

    for meta, dist in zip(resultados['metadatas'][0], resultados['distances'][0]):
        print(f"\n📘 {meta['nombre']}")
        print(f"Semestre: {meta['semestre']} | Área: {meta['area']}")
        print(f"Similitud: {1 - dist:.4f}")

def cursos_similares(nombre_curso, n=3):
    """
    Encuentra cursos similares a uno dado.
    """

    # Buscar curso base
    datos = collection.get(where={"nombre": {"$eq": nombre_curso}})

    if not datos['documents']:
        print(" Curso no encontrado")
        return

    descripcion = datos['documents'][0]

    resultados = collection.query(
        query_texts=[descripcion],
        n_results=n + 1,
        include=['metadatas', 'distances']
    )

    print(f"\n Cursos similares a {nombre_curso}:")
    print("=" * 50)

    for meta, dist in zip(resultados['metadatas'][0][1:], resultados['distances'][0][1:]):
        print(f"{meta['nombre']} | Similitud: {1 - dist:.4f}")

def buscar_por_perfil(habilidades_lista, area='especialidad'):
    """
    Busca cursos según habilidades del alumno.
    """

    consulta = " ".join(habilidades_lista)

    resultados = collection.query(
        query_texts=[consulta],
        n_results=5,
        where={"area": {"$eq": area}},
        include=['metadatas', 'distances']
    )

    print("\n Cursos según tu perfil:")
    print("=" * 50)

    for meta, dist in zip(resultados['metadatas'][0], resultados['distances'][0]):
        print(f"{meta['nombre']} | Similitud: {1 - dist:.4f}")

def menu():
    while True:
        print("\n===== SISTEMA DE RECOMENDACIÓN =====")
        print("1. Recomendar cursos")
        print("2. Cursos similares")
        print("3. Buscar por perfil")
        print("4. Salir")

        opcion = input("Seleccione una opción: ")

        if opcion == "1":
            intereses = input("Intereses: ")
            semestre = int(input("Semestre actual: "))
            recomendar_cursos(intereses, semestre)

        elif opcion == "2":
            nombre = input("Nombre del curso: ")
            cursos_similares(nombre)

        elif opcion == "3":
            habilidades = input("Habilidades (separadas por coma): ").split(",")
            buscar_por_perfil(habilidades)

        elif opcion == "4":
            print(" Saliendo...")
            break

if __name__ == "__main__":
    menu()
